// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace SneakerArt.API.Tests.Features
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class ShoesServiceTestsFeature : object, Xunit.IClassFixture<ShoesServiceTestsFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "ShoesServiceTests.feature"
#line hidden
        
        public ShoesServiceTestsFeature(ShoesServiceTestsFeature.FixtureData fixtureData, SneakerArt_API_Tests_XUnitAssemblyFixture assemblyFixture, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features", "ShoesServiceTests", "\tAs a Developer\r\n\tI want to add a new Shoe through API\r\n\tIn order to make it avai" +
                    "lable for applications.", ProgrammingLanguage.CSharp, featureTags);
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public void TestInitialize()
        {
        }
        
        public void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 6
 #line hidden
#line 7
  testRunner.Given("the Endpoint https://localhost:44379/api/v1/shoes is available", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
        }
        
        void System.IDisposable.Dispose()
        {
            this.TestTearDown();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Add Shoe with unique data")]
        [Xunit.TraitAttribute("FeatureTitle", "ShoesServiceTests")]
        [Xunit.TraitAttribute("Description", "Add Shoe with unique data")]
        [Xunit.TraitAttribute("Category", "shoe-adding")]
        public void AddShoeWithUniqueData()
        {
            string[] tagsOfScenario = new string[] {
                    "shoe-adding"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Add Shoe with unique data", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 10
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 6
 this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                            "Name",
                            "Description",
                            "Price",
                            "Img"});
                table1.AddRow(new string[] {
                            "Nike Air Force One blue",
                            "Personalized painted blue drip style slippers Available in sizes from 28 -43",
                            "$50",
                            "https://i.etsystatic.com/28924822/r/il/266da9/3400342986/il_fullxfull.3400342986_" +
                                "oh75.jpg"});
#line 11
 testRunner.When("a Post Request is sent", ((string)(null)), table1, "When ");
#line hidden
#line 14
 testRunner.Then("A Response is Received with Status 200", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
                TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                            "Id",
                            "Name",
                            "Description",
                            "Price",
                            "Img"});
                table2.AddRow(new string[] {
                            "1",
                            "Nike Air Force One blue",
                            "Personalized painted blue drip style slippers Available in sizes from 28 -43",
                            "$50",
                            "https://i.etsystatic.com/28924822/r/il/266da9/3400342986/il_fullxfull.3400342986_" +
                                "oh75.jpg"});
#line 15
 testRunner.And("a Shoe Resource is included in Response Body", ((string)(null)), table2, "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Get list of Shoes")]
        [Xunit.TraitAttribute("FeatureTitle", "ShoesServiceTests")]
        [Xunit.TraitAttribute("Description", "Get list of Shoes")]
        [Xunit.TraitAttribute("Category", "shoe-getting")]
        public void GetListOfShoes()
        {
            string[] tagsOfScenario = new string[] {
                    "shoe-getting"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Get list of Shoes", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 21
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 6
 this.FeatureBackground();
#line hidden
#line 22
 testRunner.Given("the Endpoint https://localhost:44379/api/v1/shoes is available", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 23
 testRunner.When("a Get Request is sent", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 24
 testRunner.Then("A Response is Received with Status 200", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
                TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                            "Id",
                            "Name",
                            "Description",
                            "Price",
                            "Img"});
                table3.AddRow(new string[] {
                            "1",
                            "Nike Air Force One blue",
                            "Personalized painted blue drip style slippers Available in sizes from 28 -43",
                            "$50",
                            "https://i.etsystatic.com/28924822/r/il/266da9/3400342986/il_fullxfull.3400342986_" +
                                "oh75.jpg"});
                table3.AddRow(new string[] {
                            "2",
                            "Adidas superstar shark",
                            "Personalized brown shark style sneakers Available in sizes 36 to 42",
                            "$60",
                            "https://i.pinimg.com/originals/9d/1f/b4/9d1fb4c2df48dd9726deca53db5b0efc.jpg"});
                table3.AddRow(new string[] {
                            "3",
                            "Converse all star feather",
                            "Personalized light blue feather style slippers Available in sizes 28 to 43",
                            "$55",
                            "https://i.pinimg.com/originals/d8/72/da/d872da61a31ecb0901869056d5a8d935.jpg"});
                table3.AddRow(new string[] {
                            "4",
                            "Kakashi Sneakers",
                            "Personalized Kakashi Sneakers available in sizes 8 to 9.5 US",
                            "$70",
                            "https://www.dhresource.com/0x0/f2/albu/g18/M00/2A/29/rBNaNmEXbR6AVgItAAGfK-Ikzlc5" +
                                "43.jpg"});
                table3.AddRow(new string[] {
                            "5",
                            "Nike Multicolor",
                            "Personalized Nike Multicolor Available in sizes 8 to 9.5 US",
                            "$50",
                            "https://i.pinimg.com/236x/77/2b/3c/772b3cb40434604c67b45b81d065136c.jpg"});
                table3.AddRow(new string[] {
                            "6",
                            "The Simpsons Nike Air Force",
                            "Personalized The Simpsons Nike Air Force available in sizes 8 to 9.5 US",
                            "$70",
                            "https://i.etsystatic.com/21722038/r/il/1aca43/4039489801/il_1080xN.4039489801_po7" +
                                "k.jpg"});
#line 25
 testRunner.And("a Shoe Resource is included in Response Body", ((string)(null)), table3, "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                ShoesServiceTestsFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                ShoesServiceTestsFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
